image: "dbisilm/pmdk:latest"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - grouprunner
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PMDK=ON ..
    - make -j 3
    # clean up unnecessary files and strip binaries
    - rm -rf _deps 
    - strip bench/*_bench test/*_test
  artifacts:
    paths:
      - build/
    expire_in: 30 minutes

test:
  stage: test
  tags:
    - grouprunner
  script:
    - echo pass | sudo -S mkdir -m 777 -p /mnt/pmem0/poseidon
    - cd build
    - ctest
  dependencies:
    - build

coverage:
  stage: build
  tags:
    - grouprunner
  script:
    #- dnf -y install python-pip
    - pip install gcovr --user
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_PMDK=ON -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" ..
    - make -j 3
    - echo pass | sudo -S mkdir -m 777 -p /mnt/pmem0/poseidon
    - ctest
    - ~/.local/bin/gcovr -r .. --exclude _deps --exclude "../bench/*"
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

